version: '3.4'

services:
  seriesandepisodes:
    build:
      context: .
      dockerfile: SeriesAndEpisodes/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - mongodb_container

  mongodb_container:
    image: mongo:4.2.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  ratings:
    build:
      context: .
      dockerfile: RatingsMicroservice/Dockerfile-Compose
    ports:
      - "3001:8080"
    depends_on:
      - mysql-ratingdb

  mysql-ratingdb:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: testapp
    ports:
      - "3306:3306"

volumes:
  mongodb_data_container: