version: '3.4'

services:
  series-and-episodes:
    build:
      context: .
      dockerfile: SeriesAndEpisodes/Dockerfile
    environment:
      SeriesDbSettings__SeriesCollectionName: "Series"
      SeriesDbSettings__ConnectionString: "mongodb://root:rootpassword@mongodb-seriesdb:27017"
      SeriesDbSettings__DatabaseName: "SeriesDb"
      RatingsServiceSettings__BaseAddress: "http://ratings:8080/"
    ports:
      - "3000:80"
    depends_on:
      - mongodb-seriesdb

  mongodb-seriesdb:
    image: mongo:4.2.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db

  ratings:
    build:
      context: .
      dockerfile: RatingsMicroservice/compose.Dockerfile
    environment:
      db__jdbcUrl: jdbc:mysql://mysql-ratingdb:3306/ratings
      db__username: root
      db__password: helloworld
    ports:
      - "3001:8080"
    depends_on:
      - mysql-ratingdb

  mysql-ratingdb:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: ratings
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mongodb-data:
  mysql-data: