version: '3.4'

services:
  series-and-episodes:
    build:
      context: .
      dockerfile: SeriesAndEpisodes/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - mongodb-seriesdb

  mongodb-seriesdb:
    image: mongo:4.2.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db

  ratings:
    build:
      context: .
      dockerfile: RatingsMicroservice/compose.Dockerfile
    ports:
      - "3001:8080"
    depends_on:
      - mysql-ratingdb

  mysql-ratingdb:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: ratings
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mongodb-data:
  mysql-data: