version: '3.4'

services:
  seriesandepisodes:
    build:
      context: .
      dockerfile: SeriesAndEpisodes/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - mongodb_container

  mongodb_container:
    image: mongo:4.2.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: