apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: user-db
  name: user-db
spec:
  ports:
  - name: "1433"
    port: 1433
    targetPort: 1433
  selector:
    io.kompose.service: user-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: user-db
  name: user-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: user-db
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: Your_password123
        image: mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-16.04
        name: user-db
        ports:
        - containerPort: 1433
        volumeMounts:
        - mountPath: /var/opt/mssql
          name: mssql-server-data
      restartPolicy: Always
      volumes:
      - name: mssql-server-data
        persistentVolumeClaim:
          claimName: mssql-server-data
