apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: apigateway
  name: apigateway
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: apigateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: apigateway
  name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apigateway
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: apigateway
    spec:
      containers:
      - args:
        - --log.level=DEBUG
        - --api.insecure=true
        - --providers.docker=true
        - --providers.docker.exposedbydefault=false
        - --entrypoints.web.address=:80
        image: traefik:v2.2
        name: apigateway
        ports:
        - containerPort: 80
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: apigateway-claim0
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: apigateway-claim0
        persistentVolumeClaim:
          claimName: apigateway-claim0
          readOnly: true
