apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: apigateway-claim0
  name: apigateway-claim0
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
