apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: message-queue
  name: message-queue
spec:
  ports:
  - name: "5672"
    port: 5672
    targetPort: 5672
  - name: "15672"
    port: 15672
    targetPort: 15672
  selector:
    io.kompose.service: message-queue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: message-queue
  name: message-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: message-queue
  template:
    metadata:
      labels:
        io.kompose.service: message-queue
    spec:
      containers:
      - image: rabbitmq:3.8.3-management
        name: message-queue
        ports:
        - containerPort: 5672
        - containerPort: 15672
      hostname: message-queue
      restartPolicy: Always
