apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
    traefik.enable: "true"
    traefik.http.routers.series-and-episodes-admin.entrypoints: web
    traefik.http.routers.series-and-episodes-admin.middlewares: user-service-admin
    traefik.http.routers.series-and-episodes-admin.rule: PathPrefix(`/api/admin/Series`)
      || PathPrefix(`/api/admin/Images`)
    traefik.http.routers.series-and-episodes.entrypoints: web
    traefik.http.routers.series-and-episodes.rule: PathPrefix(`/api/public/Series`)
      || PathPrefix(`/api/public/Images`)
  labels:
    io.kompose.service: series-and-episodes
  name: series-and-episodes
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 80
  selector:
    io.kompose.service: series-and-episodes
