name: .NET Core

on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master, test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
       path: ~/.nuget/packages
       key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
       restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore SeriesAndEpisodes && dotnet restore SeriesAndEpisodes.Tests
    - name: Build
      run: dotnet build SeriesAndEpisodes --configuration Release --no-restore
    - name: Test
      run: dotnet test SeriesAndEpisodes.Tests --no-restore --verbosity normal
