name: .NET Core

on:
  push:
    branches: [ master, tests ]
  pull_request:
    branches: [ master, tests ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image:  mcr.microsoft.com/dotnet/core/sdk:3.1-buster
    
    services:
      mongodb:
        image: mongo:4.2.3
        ports:
        - 27017:27017

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
       path: ~/.nuget/packages
       key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
       restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Install dependencies
      run: dotnet restore SeriesAndEpisodes && dotnet restore SeriesAndEpisodes.Tests
    - name: Build
      run: dotnet build SeriesAndEpisodes --configuration Release --no-restore
    - name: Test
      run: dotnet test SeriesAndEpisodes.Tests --no-restore --verbosity normal
      env:
        MONGODB_HOST: mongodb
        MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }}
