# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2

       - name: Cache node modules
         id: cache-node-modules
         uses: actions/cache@v2
         with:
           path: ~/.npm
           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
           restore-keys: |
                ${{ runner.os }}-node-

       - name: Install Dependencies
         if: steps.cache-node-modules.outputs.cache-hit != 'true'
         run: cd webclient && npm install

       - name: Build
         run: cd webclient && npm build

       - name: Test
         run: cd webclient && npm test
